
/* animations.js */
function drawMandala(){var canvas=document.getElementById('mandala-canvas');if(!canvas)return;var ctx=canvas.getContext('2d');var cx=150,cy=150,R=120,angle=0;var MC=['#f9b8cc','#fde7a0','#b8d4f0'];function frame(){ctx.clearRect(0,0,300,300);ctx.save();ctx.translate(cx,cy);ctx.rotate(angle);var layers=[{r:R,petals:12,color:MC[0],size:18},{r:R*.7,petals:8,color:MC[1],size:14},{r:R*.45,petals:6,color:MC[2],size:10}];layers.forEach(function(l){for(var i=0;i<l.petals;i++){var a=(Math.PI*2/l.petals)*i;ctx.save();ctx.rotate(a);ctx.beginPath();ctx.ellipse(l.r,0,l.size,l.size*.4,0,0,Math.PI*2);ctx.fillStyle=l.color;ctx.globalAlpha=.75;ctx.fill();ctx.restore();}});ctx.beginPath();ctx.arc(0,0,22,0,Math.PI*2);ctx.fillStyle='#c8963c';ctx.globalAlpha=.5;ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#7a5000';ctx.font='bold 20px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('\u0913\u0902',0,1);ctx.restore();angle+=.008;}setInterval(frame,1000/60);frame();}

function initPetals(){var canvas=document.getElementById('petals-canvas');if(!canvas)return;var ctx=canvas.getContext('2d');function resize(){canvas.width=canvas.offsetWidth;canvas.height=canvas.offsetHeight;}resize();window.addEventListener('resize',resize);var C=['#f9b8cc','#fde7a0','#fcd5b4','#b8d4f0','#d4f0c8','#ffe0ee'];function mk(fresh){return{x:Math.random()*(canvas.width||window.innerWidth),y:fresh?-20:Math.random()*(canvas.height||window.innerHeight),size:4+Math.random()*8,speedY:.6+Math.random()*1.2,speedX:(Math.random()-.5)*.8,rotation:Math.random()*Math.PI*2,rotSpeed:(Math.random()-.5)*.04,color:C[Math.floor(Math.random()*C.length)],opacity:.5+Math.random()*.45,sway:Math.random()*Math.PI*2,swaySpeed:.01+Math.random()*.02};}var petals=[];for(var i=0;i<38;i++)petals.push(mk(false));function draw(p){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rotation);ctx.globalAlpha=p.opacity;ctx.fillStyle=p.color;ctx.beginPath();ctx.ellipse(0,0,p.size,p.size*.45,0,0,Math.PI*2);ctx.fill();ctx.restore();}function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);petals.forEach(function(p,i){p.sway+=p.swaySpeed;p.x+=p.speedX+Math.sin(p.sway)*.5;p.y+=p.speedY;p.rotation+=p.rotSpeed;if(p.y>canvas.height+30)petals[i]=mk(true);draw(p);});requestAnimationFrame(animate);}animate();}

function initFloatingHearts(){var c=document.getElementById('couple-hearts');if(!c)return;var e=['\u2764\uFE0F','\uD83D\uDC95','\uD83D\uDC9B','\uD83C\uDF38','\u2728','\uD83D\uDC96'];setInterval(function(){var h=document.createElement('span');h.textContent=e[Math.floor(Math.random()*e.length)];h.style.cssText='position:absolute;left:'+(10+Math.random()*80)+'%;bottom:0;font-size:'+(14+Math.random()*16)+'px;pointer-events:none;animation:floatingHeart '+(2.5+Math.random()*2)+'s ease forwards;opacity:0;';c.appendChild(h);setTimeout(function(){h.remove();},5000);},700);}

function initCountdown(){var W=new Date('2026-06-22T11:00:00');var dEl=document.querySelector('#cd-days .cd-number'),hEl=document.querySelector('#cd-hours .cd-number'),mEl=document.querySelector('#cd-minutes .cd-number'),sEl=document.querySelector('#cd-seconds .cd-number');if(!dEl)return;var prevS=-1;function pad(n){return String(n).padStart(2,'0');}function tick(el){el.classList.remove('tick');void el.offsetWidth;el.classList.add('tick');}function update(){var diff=W-new Date();if(diff<=0){dEl.textContent=hEl.textContent=mEl.textContent=sEl.textContent='00';return;}dEl.textContent=pad(Math.floor(diff/86400000));hEl.textContent=pad(Math.floor((diff%86400000)/3600000));mEl.textContent=pad(Math.floor((diff%3600000)/60000));var s=Math.floor((diff%60000)/1000);if(s!==prevS){sEl.textContent=pad(s);tick(sEl);if(s===59)tick(mEl);prevS=s;}}update();setInterval(update,1000);}

function initScrollReveal(){var sections=document.querySelectorAll('.section-reveal');var sObs=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('visible');sObs.unobserve(e.target);}});},{threshold:.12});sections.forEach(function(s){sObs.observe(s);});var tl=document.querySelectorAll('.timeline-item[data-scroll]');var tObs=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('visible');tObs.unobserve(e.target);}});},{threshold:.2});tl.forEach(function(el){tObs.observe(el);});}

function initCountdownSparkles(){var c=document.getElementById('countdown-sparkles');if(!c)return;var cols=['#c8963c','#f9b8cc','#fde7a0','#b8d4f0'];setInterval(function(){var sp=document.createElement('div');var sz=4+Math.random()*8;sp.style.cssText='position:absolute;left:'+Math.random()*100+'%;top:'+Math.random()*100+'%;width:'+sz+'px;height:'+sz+'px;background:'+cols[Math.floor(Math.random()*4)]+';border-radius:50%;pointer-events:none;animation:sparkle '+(0.8+Math.random()*.8)+'s ease forwards;';c.appendChild(sp);setTimeout(function(){sp.remove();},1600);},250);}

function initVenueFlowers(){var c=document.getElementById('venue-flowers');if(!c)return;var fl=['\uD83C\uDF38','\uD83C\uDF3C','\uD83C\uDF3A','\uD83C\uDF3B','\uD83D\uDC90'];var pos=[{top:'10%',left:'5%'},{top:'20%',right:'8%'},{top:'60%',left:'3%'},{top:'70%',right:'5%'},{top:'40%',left:'8%'}];pos.forEach(function(p,i){var f=document.createElement('span');f.textContent=fl[i%fl.length];var css='position:absolute;font-size:'+(20+Math.random()*14)+'px;animation:venueFlowerFloat '+(3+Math.random()*2)+'s ease-in-out '+(Math.random())+'s infinite;pointer-events:none;';if(p.top)css+='top:'+p.top+';';if(p.left)css+='left:'+p.left+';';if(p.right)css+='right:'+p.right+';';f.style.cssText=css;c.appendChild(f);});}

function initFooterCanvas(){var canvas=document.getElementById('footer-canvas');if(!canvas)return;var ctx=canvas.getContext('2d');function resize(){canvas.width=canvas.offsetWidth;canvas.height=canvas.offsetHeight;}resize();window.addEventListener('resize',resize);var oc=['#f9b8cc','#fde7a0','#b8d4f0','#fcd5b4'];var orbs=[];for(var i=0;i<6;i++)orbs.push({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:40+Math.random()*80,dx:(Math.random()-.5)*.4,dy:(Math.random()-.5)*.4,color:oc[Math.floor(Math.random()*4)],alpha:.08+Math.random()*.12});function animate(){ctx.clearRect(0,0,canvas.width,canvas.height);orbs.forEach(function(o){o.x+=o.dx;o.y+=o.dy;if(o.x<0||o.x>canvas.width)o.dx*=-1;if(o.y<0||o.y>canvas.height)o.dy*=-1;var g=ctx.createRadialGradient(o.x,o.y,0,o.x,o.y,o.r);g.addColorStop(0,o.color);g.addColorStop(1,'transparent');ctx.globalAlpha=o.alpha;ctx.fillStyle=g;ctx.beginPath();ctx.arc(o.x,o.y,o.r,0,Math.PI*2);ctx.fill();});ctx.globalAlpha=1;requestAnimationFrame(animate);}animate();}

document.addEventListener('DOMContentLoaded',function(){drawMandala();initScrollReveal();initCountdown();initCountdownSparkles();initVenueFlowers();});
window.initHeroAnimations=function(){initPetals();initFloatingHearts();initFooterCanvas();};
